### ISSUE TITLE
[maybe issue] CSAT teleporting to a wrong position

### ISSUE THREAD

**Issue by StefArma** [A3Antistasi/Antistasi-WotP#28]
*Version:* 0.11.2

*Mods:* CBA, TFAR, ACE no medical

*Environment*:  MP dedi.

*.rpt attatched?* Nothing on it

*have you edited the missionfile?*: No

***Issue:***
CSAT outpost spawned have their units teleported to another point (in this case Factory), in other cases this bug don't appear

Screenshots: https://imgur.com/a/1Aqwu

**Comment by Barbolani77** [comment]
I would bet it is related to the bug on which you see blue marker while the zone is red, and those units were the Factory garrison.

In order to check it. You have to do the following, assuming you know the name of the marker:

First know the engine marker side: exec locally: hint format ["%1",lados getVariable markername];

If the marker belongs to NATO then we have to check if the CSAT units are spawned by this marker. If belongs to CSAT, it's confirmed we have an issue with the marker colors, nothing else.

Exec globally (its hard with HCs, you will have to have only one HC, if not is not reliable):

pepe = [];
pepe = allUnits select {(local _x) and (side _x == muyMalos) and (_x getVariable ["marcador",""] == markerName)};
if (count pepe > 0) then {juan = [] + pepe; publicVariable "juan"};

Now exec locally:

hint format ["%1",juan];

In variable juan you have all the units which are supposed to be garrison of that place and do stuff with them.
